general {
    disable_loading_bar = true
    hide_cursor = true
    immediate_render = true
}

background {
    monitor =
    path = ~/.local/share/simple-custom-arch/majula-wallpaper.png
    color = rgb(0E1114)
    blur_passes = 1
    blur_size = 4
}

label {
    monitor =
    text = cmd[update:1000] date +"%H:%M"
    color = rgb(DDD6C6)
    font_size = 64
    font_family = Noto Sans
    position = 0, 120
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgb(A39B8C)
    font_size = 16
    font_family = Noto Sans
    position = 0, 65
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 48
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.32
    outer_color = rgb(E0783E)
    inner_color = rgb(171C20)
    font_color = rgb(DDD6C6)
    check_color = rgb(D1A35C)
    fail_color = rgb(C06452)
    fail_text = <b>Authentication failed</b>
    placeholder_text = <i>Password</i>
    rounding = 6
    position = 0, -40
    halign = center
    valign = center
}
