# Majula semantic palette
background #0E1114
foreground #DDD6C6
selection_background #D1A35C
selection_foreground #0E1114
cursor #E0783E
cursor_text_color #0E1114
url_color #7899A2
active_border_color #E0783E
inactive_border_color #465056
active_tab_background #20272C
active_tab_foreground #DDD6C6
inactive_tab_background #171C20
inactive_tab_foreground #A39B8C
bell_border_color #C06452

color0 #0E1114
color1 #C06452
color2 #87996D
color3 #D1A35C
color4 #7899A2
color5 #A39B8C
color6 #465056
color7 #DDD6C6
color8 #20272C
color9 #E0783E
color10 #87996D
color11 #D1A35C
color12 #7899A2
color13 #A39B8C
color14 #7899A2
color15 #DDD6C6

enable_audio_bell no
confirm_os_window_close 0
tab_bar_style powerline
tab_powerline_style slanted
window_padding_width 6
background_opacity 0.84
